import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // chatSidebar: [
  //   {type: 'autogenerated', dirName: '.'}
  // ],

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'septopus',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Meta Septopus',
      items: [
        {
          type: 'autogenerated',
          dirName: 'world',
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Rules Center',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'rules',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'King Center',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'king',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'AI Center',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'ai',
    //     },
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Release History',
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'versions',
    //     },
    //   ],
    // },
    {
      type: 'category',
      label: 'Dev Log',
      items: [
        {
          type: 'autogenerated',
          dirName: 'record',
        },
      ],
    },
  ],
};

export default sidebars;
